version: "3.1"
services:
  ajenti:
    restart: always
    image: algonrey/prp
    container_name: ajenti
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./nginx/:/etc/nginx/
      - ./ajenti/:/etc/ajenti/
      - /home/docker/blog/public/:/etc/blog/
      - ./www/:/etc/www/
